### ISSUE TITLE
Incorect Copyright tags

### ISSUE THREAD

**Issue by volodymyrdovhan** [rezeau/moodle-qtype_multianswerrgx#1]
Hello,
please review the requirements for how copyright tags should be defined in each file:
https://moodledev.io/general/community/plugincontribution/checklist#copyrights

![image](https://github.com/user-attachments/assets/e578d8fd-80e3-4b8d-9e91-93579dfcf27a)
![image](https://github.com/user-attachments/assets/b6682e68-ca35-497c-9093-371604cef98a)
![image](https://github.com/user-attachments/assets/c44fafb7-c2d5-4c3f-8566-1adf709b53a9)
![image](https://github.com/user-attachments/assets/0a5a1cdb-ad35-4dac-9129-81e8e57a0158)
![image](https://github.com/user-attachments/assets/76b06dba-ab0c-41b9-a979-878a3cdd6735)

**Comment by rezeau** [comment]
hi @volodymyrdovhan I have fixed (and committed) issues n° 1 and n°2 as per your request.
Unfortunately just noticed that [Moodle Plugin CI throws errors](https://github.com/rezeau/moodle-qtype_multianswerrgx/actions/workflows/moodle-ci.yml). I'll have a look at the problem.

**Comment by rezeau** [comment]
Closing now since this plugin has been validated.
