### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by volodymyrdovhan** [rezeau/moodle-qtype_multianswerrgx#2]
Hello,
Please clean up the code and remove the variables/functions/methods that are not used, commented code, etc.

![image](https://github.com/user-attachments/assets/c0ee4721-f503-45ff-8e37-880fe5ba87e9)
![image](https://github.com/user-attachments/assets/216eb1f0-6e79-4e1a-8e78-89cc2d09135f)
![image](https://github.com/user-attachments/assets/ff2dc729-50d8-425a-8e18-a5f834a3c3f3)

**Comment by rezeau** [comment]
Closing now since this plugin has been validated.
